//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class Batch
    {
        
        public Batch()
        {
            this.BatchJobs = new HashSet<BatchJob>();
            this.BatchRuns = new HashSet<BatchRun>();
        }
    
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
       
    
       
        public ICollection<BatchJob> BatchJobs { get; set; }
       
        public ICollection<BatchRun> BatchRuns { get; set; }
    }
}
