//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class Claim
    {
        
        public Claim()
        {
            this.ClaimDrugs = new HashSet<ClaimDrug>();
            this.ClaimServices = new HashSet<ClaimService>();
        }
    
        public int Id { get; set; }
        public int ProviderId { get; set; }
        public int Enrolleeid { get; set; }
        public string enrolleeFullname { get; set; }
        public string enrolleeGender { get; set; }
        public string enrolleeCompanyName { get; set; }
        public int enrolleeCompanyId { get; set; }
        public string enrolleePolicyNumber { get; set; }
        public string EnrolleePlan { get; set; }
        public string ClaimsSerialNo { get; set; }
        public string EVSCode { get; set; }
        public string DoctorsName { get; set; }
        public string DoctorsId { get; set; }
        public string AreaOfSpecialty { get; set; }
        public string Signature { get; set; }
        public bool DoctorSigned { get; set; }
        public DateTime DoctorSignecDate { get; set; }
        public string specialistName { get; set; }
        public string AreaOfSpecialtyforspecialist { get; set; }
        public string specialistphonenumber { get; set; }
        public bool specialistSigned { get; set; }
        public DateTime specialistSignecDate { get; set; }
        public DateTime ServiceDate { get; set; }
        public DateTime AdmissionDate { get; set; }
        public DateTime DischargeDate { get; set; }
        public string Durationoftreatment { get; set; }
        public string Diagnosis { get; set; }
        public string TreatmentGiven { get; set; }
        public string TreatmentCode { get; set; }
        public string referalCode { get; set; }
        public bool enrolleeSigned { get; set; }
        public DateTime EnrolleeSignDate { get; set; }
        public bool AllprescibedDrugs { get; set; }
        public bool LaboratoryInvestigation { get; set; }
        public bool Admission { get; set; }
        public bool Feeding { get; set; }
        public string Note { get; set; }
        public string Tag { get; set; }
        public int capturedBy { get; set; }
        public string capturedName { get; set; }
        public int vettedBy { get; set; }
        public int RevettedBy { get; set; }
        public DateTime VettedDate { get; set; }
        public DateTime ReVettedDate { get; set; }
        public string status { get; set; }
        public System.Guid Guid { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public int ClaimBatchId { get; set; }
       
        public string enrolleeage { get; set; }
        public string ClientsideID { get; set; }
        public string diagnosticsIDString { get; set; }
        public bool SubmitByProvider { get; set; }
        public string ipaddressofprovider { get; set; }
        public string vettedName { get; set; }
        public int MyUserId { get; set; }
    
        public  ClaimBatch ClaimBatch { get; set; }
       
        public ICollection<ClaimDrug> ClaimDrugs { get; set; }
       
        public ICollection<ClaimService> ClaimServices { get; set; }
    }
}
