//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class ClaimHistory
    {
        public int Id { get; set; }
        public string PROVIDER { get; set; }
        public string LOCATION { get; set; }
        public string CLIENTNAME { get; set; }
        public string COMPANY { get; set; }
        public string POLICYNUMBER { get; set; }
        public string HEALTHPLAN { get; set; }
        public DateTime ENCOUNTERDATE { get; set; }
        public DateTime DATERECEIVED { get; set; }
        public string DIAGNOSIS { get; set; }
        public string CLASS { get; set; }
        public decimal AMOUNTSUBMITTED { get; set; }
        public decimal AMOUNTPROCESSED { get; set; }
        public string TREATMENT { get; set; }
        public System.Guid Guid { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
       
        public int PROVIDERID { get; set; }
        public int SerialNo { get; set; }
    }
}
