//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class ConnectcarePaymentDetail
    {
        public int Id { get; set; }
        public string paymentid { get; set; }
        public int sponsorID { get; set; }
        public string sponsorIDString { get; set; }
        public string beneficiaryID { get; set; }
        public string policyid { get; set; }
        public decimal amountpaid { get; set; }
        public string planpurchased { get; set; }
        public bool addon { get; set; }
        public DateTime paymentDate { get; set; }
        public System.Guid Guid { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
       
    }
}
