//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class EnrolleeVerificationCode
    {
        public int Id { get; set; }
        public int EnrolleeId { get; set; }
        public string Status { get; set; }
        public string VerificationCode { get; set; }
        public DateTime EncounterDate { get; set; }
        public DateTime DateAuthenticated { get; set; }
        public DateTime DateExpired { get; set; }
        public int Channel { get; set; }
        public string RequestPhoneNumber { get; set; }
        public int CreatedBy { get; set; }
        public int VisitPurpose { get; set; }
        public int ProviderId { get; set; }
        public string Note { get; set; }
        public System.Guid Guid { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
       
        public int AuthChannel { get; set; }
        public bool Pickedup { get; set; }
        public int PickedUpById { get; set; }
        public bool AttendedTo { get; set; }
        public DateTime DateAttendedTo { get; set; }
        public string ServiceAccessed { get; set; }
        public bool AuthorizationCodeGiven { get; set; }
        public string AuthorizationCode { get; set; }
        public int AuthorizedByUserId { get; set; }
        public DateTime DateAuthorized { get; set; }
        public string AgentNote { get; set; }
        public bool PostSMSSent { get; set; }
        public string visittype { get; set; }
    }
}
