//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class Issue
    {
        public int Id { get; set; }
        public string subject { get; set; }
        public string Details { get; set; }
        public string status { get; set; }
        public string providers { get; set; }
        public string companies { get; set; }
        public string prority { get; set; }
        public string users { get; set; }
        public string report { get; set; }
        public bool escalated { get; set; }
        public System.Guid Guid { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
       
    }
}
