//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class PaymentBatch
    {
        
        public PaymentBatch()
        {
            this.ClaimBatches = new HashSet<ClaimBatch>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public string status { get; set; }
        public DateTime datepaymentstarted { get; set; }
        public DateTime datepaymentcompleted { get; set; }
        public DateTime terminationdate { get; set; }
        public int paidby { get; set; }
        public int createdBy { get; set; }
        public System.Guid Guid { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
       
        public int terminatedby { get; set; }
    
       
        public ICollection<ClaimBatch> ClaimBatches { get; set; }
    }
}
