//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class Sm
    {
        public int Id { get; set; }
        public string Msisdn { get; set; }
        public int EnrolleeId { get; set; }
        public string FromId { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public DateTime DeliveryDate { get; set; }
        public DateTime DateDelivered { get; set; }
        public string ServerResponse { get; set; }
        public string ServerCode { get; set; }
        public string ServerStatus { get; set; }
        public int CreatedBy { get; set; }
        public System.Guid Guid { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
       
    }
}
