//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class State
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public long Zone { get; set; }
        public bool Status { get; set; }
        public System.Guid Guid { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
       
        public int EnrolleeDetailsPageId { get; set; }
        public int EnrolleeListPageId { get; set; }
        public int EnrolleePageId { get; set; }
        public int ProviderPageId { get; set; }
        public int EnrolleeRegPageId { get; set; }
        public int DelistedProviderPageId { get; set; }
    
        
    }
}
