//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoClasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class Subscription
    {
        public int Id { get; set; }
        public string SubscriptionCode { get; set; }
        public int CompanyId { get; set; }
        public string Companyplans { get; set; }
        public DateTime Startdate { get; set; }
        public int Duration { get; set; }
        public DateTime Expirationdate { get; set; }
        public string Note { get; set; }
        public int Status { get; set; }
        public int Createdby { get; set; }
        public int AuthorizationStatus { get; set; }
        public string AuthorizationNote { get; set; }
        public string DisapprovalNote { get; set; }
        public string TerminationNote { get; set; }
        public int Terminatedby { get; set; }
        public int AuthorizedBy { get; set; }
        public int DisapprovedBy { get; set; }
        public DateTime AuthorizedDate { get; set; }
        public DateTime DisapprovalDate { get; set; }
        public System.Guid Guid { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
       
        public string SubscriptionMode { get; set; }
        public string Subsidiaries { get; set; }
        public int SubsidiaryId { get; set; }
    }
}
